biegl/web-abfaltersbach-at

- app/Navigation.php
- app/Page.php
- database/factories/NavigationFactory.php
- database/factories/PageFactory.php
- database/migrations/2020_04_07_091638_create_pages_table.php
- database/migrations/2020_04_08_123724_create_navigation_table.php
- tests/CreatesApplication.php
- tests/Feature/RouterTest.php
> Add basic tests for router

- app/File.php
- config/filesystems.php
- resources/views/layouts/base.blade.php
- resources/views/partials/files.blade.php
- Added file meta information
- Used disk('attachments') to locate uploaded filesr
> Add human readable file meta info

- .github/workflows/deploy.yml
> Fix deployment script

- app/Exceptions/Handler.php
- composer.json
- composer.lock
- config/sentry.php
- resources/lang/de/passwords.php
- Added sentry.io for logging
- Fixed typo in translation key
> Add sentry

- app/Event.php
- app/Http/Controllers/Api/EventsController.php
- app/Http/Controllers/Api/NewsController.php
- app/Http/Controllers/Api/PagesController.php
- app/Http/Controllers/PageController.php
- app/Http/Requests/StorePage.php
- app/News.php
- app/Page.php
- database/migrations/2020_04_07_091638_create_pages_table.php
- resources/easyadmin/.eslintrc.js
- resources/easyadmin/src/App.vue
- resources/easyadmin/src/components/EventEntryForm.vue
- resources/easyadmin/src/components/PageEntryForm.vue
- resources/easyadmin/src/models/event.ts
- resources/easyadmin/src/models/file.ts
- resources/easyadmin/src/models/news.ts
- resources/easyadmin/src/models/page.ts
- resources/easyadmin/src/models/user.ts
- resources/easyadmin/src/router/index.ts
- resources/easyadmin/src/services/page.service.ts
- resources/easyadmin/src/store/events.module.ts
- resources/easyadmin/src/store/file.module.ts
- resources/easyadmin/src/store/index.ts
- resources/easyadmin/src/store/news.module.ts
- resources/easyadmin/src/store/pages.module.ts
- resources/easyadmin/src/views/Login.vue
- resources/easyadmin/src/views/Pages.vue
- resources/easyadmin/src/views/User.vue
- routes/api.php
- Addes admin area for maintaining pages
> Add support for maintaining pages

- app/Event.php
- Increased number of events displayed
> Increase number of events shown

- app/Http/Kernel.php
- tests/Feature/LoginTest.php
- fix: Start session for api middleware group
> Start session for API middleware group

- app/Models/Page.php
- resources/views/partials/modules/list.blade.php
- fixed: Partial not loading due to misread model name
> Fix content modules

- app/Notifications/EventCreated.php
- app/Notifications/NewsCreated.php
- fix: Change link target of telegram messages to landing page
> Change link targets

- .github/workflows/compress_images.yml
- feat: Added workflow to automatically compress images
> Enable image compression

- .github/workflows/compress_images.yml
> Add automerge label

- app/Http/Filters/EventFilter.php
- app/Http/Filters/NewsFilter.php
- app/Http/Filters/QueryFilter.php
- app/Models/Event.php
- app/Models/News.php
- app/Models/Page.php
- app/Notifications/EventCreated.php
- app/Notifications/NewsCreated.php
- app/Traits/HasFilters.php
- config/app.php
- resources/views/page/home.blade.php
- resources/views/partials/eventlist.blade.php
- resources/views/partials/newslist.blade.php
- resources/views/partials/wahlkarten.blade.php
- Add direct link to telegram messages. The linked news entry will be displayed on the page.
- Added link to wahlkartenantrag.at
> Add telegram direct link

- app/Models/Page.php
- Attachments are now sorted by creation date
> Sort attachments by creation date

- resources/views/page/home.blade.php
> chore: remove wahlkarten.at

- composer.json
- resources/views/page/home.blade.php
- Update template to include partial
> Add link Wahlkartenantrag

- app/Providers/ViewServiceProvider.php
- config/app.php
- resources/views/partials/header.blade.php
Updates the main header image automatically based on current month.
Months 1,2,3,12 will show the winter image, while the rest shows the summer image.
> Set main header image

- .github/workflows/deploy.yml
- Updated php version to 8.1
- Removed deprecated composer flag
> Update deploy php version

- public/admin/.htaccess
- Fixed an issue with the htaccess syntax after php 8.1 update
> Fix htaccess syntax

- .github/workflows/phpstan.yml
- .github/workflows/snyk_reviewer.yml
- .github/workflows/test.yml
- Allows phpstan code linter to fail
- Update ubuntu version
- Auto approve snyk PRs
> CI updates

- app/Notifications/NewsCreated.php
- routes/web.php
Resolves https://biegl.sentry.io/issues/5139975799/?project=5413876&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
> Fix issue with posting telegram images

- app/Notifications/NewsCreated.php
Fixes an issue where a domain is not set correctly when posting to telegram.
> Issue with domain not set correctly
